### PR TITLE
Update admin.js

### PR DESCRIPTION
**Pull request by jkraffthha**
Fix display of themes and plugins in NC26 and NC27

### CODE REVIEW

**Comment by PhrozenByte** [comment]
As always, even though I had no time to spare, computers feel that and make things hard, but I managed to get CI working again (at least for stable Nextcloud 26 and 27, tests on `master` are still broken, no idea why, but no time for that...) and merge this PR.

Thank you for your contribution!

However, **I did not test your changes!** Please install the app from the `cms_pico-1.0` branch (note that `master` is the dev version of v2.0 - which isn't going to work...) and test it. Then please give me some feedback whether it works and I'll publish a new version (which hopefully still works and doesn't require too much work to get things going again, too...).

**Comment by jkraffthha** [comment]
I've tested changes on NC25, NC26 and NC27.
However, I should point that I'm a bit puzzled about the origin of the problem.
It seem that the 'destroy' method is available in Bootstrap 3.4.1 and 'dispose' in Bootstrap 5.3, so 'dispose' should actually be the right method for the job.
Did Nextcloud or Pico reverted to an older version of Bootstrap at some point ?!
I don't know much about PHP, JS and bootstrap but this make me think that, beyond the quick fix to make it work in the current state of things, it might be necessary to address the issue looking at the Bootstrap version to avoid any future disruptions.

Note: I have tested it using the currently available version in the nextcloud app store (1.0.21), just changing the necessary line of code.

**Comment by PhrozenByte** [comment]
> Did Nextcloud or Pico reverted to an older version of Bootstrap at some point ?!

Nextcloud switched to Vue for its UI some time ago and dropped pre-shipped dependencies like jQuery, Bootstrap, etc. Nextcloud did (and is still doing) a lot backwards incompatible changes to its UI a few major releases ago. I'd say that it's rather surprising that the app's settings page still works... Since I don't have enough free time to fully maintain this project and nobody took responsibility yet, it's likely that this will completely break at some point in the future. The only real solution is to rewrite the app's settings pages from scratch using Vue. PRs are welcome.

> Note: I have tested it using the currently available version in the nextcloud app store (1.0.21), just changing the necessary line of code.

Can you please test it on a fresh Nextcloud installation (i.e. without any other non-default apps) with a clean Pico CMS for Nextcloud app installed from the `cms_pico-1.0` branch? Thanks :+1:

**Comment by jkraffthha** [comment]
OK, took some time to test it with a fresh install. Fresh server qith fresh Nextcloud install.
Installed the CMS_PICO from app store, changed the line 205 in the admin.js, works perfectly.
That's pretty much all I can do for now.
Any plans on pushing this particular fix onto the store ?

**Review by ahm507 — COMMENTED** [review]
I tried the change on NC 28 and it is working fine

**Comment by PhrozenByte** [comment]
> I tried the change on NC 28 and it is working fine

Did you just apply the fix to the latest app version on an existing Nextcloud instance? Or did you, as instructed above, actually run a manual app install (see [`README.md`](https://github.com/nextcloud/cms_pico?tab=readme-ov-file#manually)) from the `cms_pico-1.0` branch (use `git clone -b cms_pico-1.0 https://github.com/nextcloud/cms_pico.git apps/cms_pico`) on a fresh Nextcloud instance running stable versions 26, 27 and 28? To publish a new release we need the latter including manual testing of all the app's basic functionality.

**Comment by ahm507** [comment]
No. I applied the fix manually but using docker. I tried only using image nextcloud:28.0.2-apache. 
I did basic testing but around cms_pico. I am not sure about your standards for the testing required. I will read more about nextcloud contribution and may be do it again

**Comment by noci2012** [comment]
NC29: next error in debug:
[cms_pico] Debug: /appinfo/app.php is deprecated, use \OCP\AppFramework\Bootstrap\IBootstrap on the application class instead.
	GET /apps/logreader/api/poll?lastReqId=eVXRM7carbBsNv2ICrov

cms_pico seems to operate.

**Pull request merged**
