### PR TITLE
Refactor StorageFolder::newFile() and newFolder()

### LINKED ISSUE #141: problems with local external storage?
Hi, I just installed picocms to try it out and got the following error message while trying to create a new test-site with a user.
Which is strange because my user has the permission to create folders in there.
(I am using local external storage with picocms 1.0.9 on NC19.0.2)
Please tell me if you need more infos (and please which ones)

`{"reqId":"rDCUL26nlqEJ3R9F69Yl","level":2,"time":"2020-09-11T11:22:34+02:00","remoteAddr":"87.123.152.204","user":"Simon","app":"cms_pico","method":"POST","url":"/apps/cms_pico/personal/websites","message":{"Exception":"OCP\\Files\\NotPermittedException","Message":"No create permission for folder","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/cms_pico/lib/Files/StorageFolder.php","line":143,"function":"newFolder","class":"OC\\Files\\Node\\Folder","type":"->"},{"file":"/var/www/nextcloud/apps/cms_pico/lib/Service/TemplatesService.php","line":261,"function":"newFolder","class":"OCA\\CMSPico\\Files\\StorageFolder","type":"->"},{"file":"/var/www/nextcloud/apps/cms_pico/lib/Service/WebsitesService.php","line":142,"function":"installTemplate","class":"OCA\\CMSPico\\Service\\TemplatesService","type":"->"},{"file":"/var/www/nextcloud/apps/cms_pico/lib/Controller/WebsitesController.php","line":112,"function":"createWebsite","class":"OCA\\CMSPico\\Service\\WebsitesService","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":170,"function":"createPersonalWebsite","class":"OCA\\CMSPico\\Controller\\WebsitesController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":137,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":297,"function":"call_user_func"},{"file":"/var/www/nextcloud/lib/base.php","line":1012,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/lib/private/Files/Node/Folder.php","Line":171,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36","version":"19.0.2.2","id":"5f5b439e830f1"}`

### PR DESCRIPTION
**Pull request by PhrozenByte**
Nextcloud's file operations API apparently is unable to proberly deal with relative paths (even though the docs tell us otherwise). It …
1. performs file permission checks on the base directory rather than the respective parent directory (:confused:), causing #141, and
2. blocks relative paths like `..` (likely as a security measure - [by using the most unsophisticated approach](https://github.com/nextcloud/server/blob/5fb909faa536ba29ace9f78c1d1c4cb253c37fe4/lib/private/Files/Node/Node.php#L331-L333) :unamused:).

Also see nextcloud/server#26396.

Fixes #141 #165

@szaimen @matrois: Since I still don't know what exactly you guys are doing to cause this issue, I couldn't test it. Please give it a try.

### CODE REVIEW

**Comment by szaimen** [comment]
Unfortunately I cannot test this since I get
```
error: patch failed: lib/Files/LocalFolder.php:153
error: lib/Files/LocalFolder.php: patch does not apply
```
when I try to apply the patch...

**Comment by szaimen** [comment]
@PhrozenByte if you want to test this yourself you should be able to reproduce this issue by following: https://github.com/nextcloud/android/issues/8010#issuecomment-789677269

**Comment by PhrozenByte** [comment]
No need to apply the patch manually, simply clone the branch (or download the source ZIP from https://github.com/nextcloud/cms_pico/archive/refs/heads/bugfix/141.zip) and run `composer install`.

**Comment by szaimen** [comment]
Thanks I've done that in a VM and I can report that it fixes my issues with read only root folder. Thank you! :)

**Comment by PhrozenByte** [comment]
Let's give @matrois a few more days to test this, too.

**Pull request merged**
